// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/option-chain-builder/OptionChainBuilder.tsx": () => import("../components/mockups/option-chain-builder/OptionChainBuilder.tsx")
};
